M48
; DRILL file {KiCad (6.0.5-0)} date Sunday, September 18, 2022 at 01:29:48 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-18T01:29:48-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0787
%
G90
G05
T2
X3.0302Y-2.1592
T1
G00X3.0204Y-1.9859
M15
G01X3.04Y-1.9859
M16
G05
T0
M30
